version: '3'
services:
    learning-tool:
        build: learning-tool
        volumes:
            - $PATH_DATA:/data
            - ./learning-tool/src:/opt/learning-tool
            - $PATH_MODELS:/models
